### ISSUE TITLE
Expecting one type of key only

### ISSUE THREAD

**Issue by DubbaThony** [VOID404/ssh-key-manager#1]
Given this - https://github.com/VOID404/ssh-key-manager/blob/main/src/Lib.hs#L22
program expects all keys to be `ssh-rsa` keys, when other key type is met, application won't work as expected.

For example, generate Ed25519 key and try adding this key into your authorized_keys file, and try to run the app.

**Comment by VOID404** [comment]
Should be fixed now, thank you for feedback
